[package]
name = "bench-parmesan"
version = "0.0.8"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parmesan = { path = "../parmesan", features = ["measure"] }    #   features = [""]   measure
colored = "2.0.0"
rayon = "^1.5.1"
chrono = "^0.4.0"

[features]
pbs = []
add = []
sgn = ["add"]
max = []
mul = ["mul_light"]
squ = ["squ_light"]
mul_light = []
squ_light = []
scm = []
nn  = []
all = ["pbs", "add", "sgn", "max", "mul", "squ", "scm", "nn"]
default   = ["pbs", "add", "sgn", "max", "mul_light", "squ_light", "scm"]
log_ops = ["parmesan/log_ops"]
