[package]
name = "bench-parmesan"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#DBG
concrete = { path = "../concrete-lib/concrete", features = ["unsafe"] }
parmesan = { path = "../parmesan", features = ["measure"] }    #DBG   meaure   sequential
colored = "2.0.0"
rayon = "^1.5.1"
