[package]
name = "bench-parmesan"
version = "0.0.7"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parmesan = { path = "../parmesan" }    #   meaure   sequential
colored = "2.0.0"
rayon = "^1.5.1"

[features]
add = []
sgn = ["add"]
max = []
mul = []
scm = []
nn  = []
default   = ["add", "sgn", "max", "mul", "scm", "nn"]
