[package]
name = "bench-parmesan"
version = "0.0.8"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parmesan = { path = "../parmesan" }
colored = "2.0.0"
rayon = "^1.5.1"
chrono = "^0.4.0"

[features]
pbs         = []
add         = []
sgn         = ["add"]
max         = []
mul         = ["mul_light"]
squ         = ["squ_light"]
mul_light   = []
squ_light   = []
scm         = []
nn          = []
all         = ["pbs", "add", "sgn", "max", "mul", "squ", "scm", "nn"]
default     = ["pbs", "add", "sgn", "max", "mul_light", "squ_light", "scm"]
measure     = []                                # measure is needed for measure_duration! which is used instead of simple_duration! in cases where there is no measure_duration! inside the block
log_ops     = ["measure", "parmesan/log_ops"]
